# Document:
# http://simiki.org/docs/configuration.html

url: https://doctording.github.io/code/
title: 剑指Offer
keywords: algorithm，python
description: for python and algorithm
author: doctording

root: /code/
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: linux  # the category directory name
    label: Linux/运维  # alias name of category, used in index page
  - name: database
    label: 数据库

deploy:
  - type: git
    remote: https://doctording.github.io/code/
    branch: gh-pages  

default_ext: md
pygments: true
debug: false